"on":
    push:
        branches:
            - main
name: Deploy to fdvwabbg
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: exec porter apply
              env:
                PORTER_APP_NAME: fdvwabbg
                PORTER_CLUSTER: "1"
                PORTER_DEPLOYMENT_TARGET_ID: 008d4a34-c94c-425b-b35c-6955a7ec55ab
                PORTER_HOST: https://witt.withporter.run
                PORTER_PR_NUMBER: ${{ github.event.number }}
                PORTER_PROJECT: "1"
                PORTER_REPO_NAME: ${{ github.event.repository.name }}
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_1_1 }}
